general.import = ["theme-kanagawa-wave.toml"]

[window]
padding = { x = 10, y = 10 }
dynamic_title = true

[font]
size = 12

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Liga SFMono Nerd Font"
style = "Bold Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Normal"
