modmap:
  - name: CapsLock to Esc/Alt
    remap:
      CapsLock:
        held: Alt_L
        alone: Esc
keymap:
  - name: Alt+IJKL to Arrow Keys
    remap:
      Alt-k: Up
      Alt-j: Down
      Alt-h: Left
      Alt-l: Right
