modmap:
  - name: CapsLock to Esc/Ctrl
    remap:
      CapsLock:
        held: Ctrl_L
        alone: Esc
keymap:
  - name: Ctrl+IJKL to Arrow Keys
    remap:
      C-k: Up
      C-j: Down
      C-h: Left
      C-l: Right
