#!/usr/bin/env zsh

logger "Switched to battery mode"

hyprctl --instance 0 keyword animations:enabled 0
hyprctl --instance 0 keyword decoration:drop_shadow 0
hyprctl --instance 0 keyword decoration:blur:enabled 0
